### PR TITLE
Namespaces, Zen Garden demo

### PR DESCRIPTION
**Pull request by mambax7**

### CODE REVIEW

**Comment by MichelChouinard** [comment]
Nice,

Never had time to get to it.

Question, have you tested it on PHP 7+?

**Comment by mambax7** [comment]
Yes,  PHP 7.2.8

**Comment by mambax7** [comment]
This demo runs on PHP 7.1.6: http://demo.xoops.org/puremvc-multicore/

**Comment by MichelChouinard** [comment]
The demo is fast! Cool.

**Comment by mambax7** [comment]
Please review the code and make any improvements that you see fit. This was just a quick and dirty conversion to namespaces, and to make the demo work, but I didn't try to make any other changes, so I am sure that there are more things that could be done with the namespaces to make the code look and work better, and you're the best person to make it happen.

**Comment by MichelChouinard** [comment]
It's been a long time since I worked on this project.  

- Never was able to convince employers/co-workers to use it.
- Lack of contributors to keep the project fully alive.

I'll check that in my spare time.  For now, GitHub say that there is no conflicts but I do not have control over this repository to merge your request.  I will download, your copy and check it.  Plus, I'm sure that there is way more things that can be optimized for PHP 7 and are worth investigating.

**Comment by mambax7** [comment]
@cliffhall will merge it, but he'll feel more comfortable if you review it and approve it. 
And you're absolutely right - optimizing it for PHP7 would be very nice - hopefully some PHP experts will jump in and help you in doing it.

**Comment by MichelChouinard** [comment]
@cliffhall I'll try to check this and come back to you.

**Comment by cliffhall** [comment]
Caveat: optimization for PHP 7 shouldn’t break previous versions. The tests should still run on all supported versions of PHP.

**Comment by mambax7** [comment]
PHP 7.1+ are the only versions actively supported.  PHP 5.6 is getting only security updates:
http://php.net/supported-versions.php

Since PHP 7.1 active support will end on December 1st this year, PHP 7.2+ should be clearly the focus of any future development and optimization, with the changes officially being released after 12/1/2018 :)

**Comment by MichelChouinard** [comment]
@cliffhall I know.  This is why I asked you if it could be added as a branche for now.  The use of namespaces is a breaking change by itself on older version of PHP.  They were introduced for PHP 5 >= 5.3.0, PHP 7.  I have no stats on usage of the framework to tell.  That's why I didn't implement them at the time.

But, at some point, we will have to address that.  We could keep the current version as is in a release version and make sure to document accordingly.  After that, introduce a new release that use name-spacing with no optimisation for PHP 7 but will work in PHP 5.3 ­­>.  The full optimisation for PHP 7> would be in another release.  This way we won't have to manage multiple repository for each versions.

No, puremvc-php533-multicore-framework repository. Neither puremvc-php7-multicore-framework, etc...  Just one puremvc-php-multicore-framework with release tags.  Same thing for all utilities.

There is still a lot of work to do...  The framework is good as is, but stuff is missing.  Ex: routing, optimized DB adapters, etc...  Those things comparing to other frameworks are the main reason I was never able to convince peoples around me to use it. Even if I told them, at the time, that it was the force of the framework...  Create your own routing or use one already existing, etc...  Use the framework to manage the MVC part with the bonus of the multi-core enabling full modular development.

**Comment by MichelChouinard** [comment]
Also.  The current demo isn't a good representation of what could be achieved with the use of the framework.

**Comment by MichelChouinard** [comment]
I know that.  The thing is that we do not have stats about who is running
past version currently.  So we must not introduce breaking changes in the
master without a way for users to have easy access to the older versions.

Le sam. 4 août 2018, à 11 h 26, Michael Beck <notifications@github.com> a
écrit :

**Comment by MichelChouinard** [comment]
@cliffhall 
This merge is a big change on the v1.0.0.  

You should have created a branch v1.0.0, a tag v1.0.0 with a release for it mentioning tested on PHP 5.3.

Now that the merge is done.  Can you at least create the v1.1.0 branch, tag and release.

**Comment by MichelChouinard** [comment]
In fact...  A goo structure should be.

**Master** pointing on latest stable release.
**Dev** current development version and default branch

and a branch, tag and release for each stable version revision.

My two cent...

**Comment by cliffhall** [comment]
Hi Michael,

I did tag 1.1.0. There is no separate branch for it, because it’s not under continual development.

**Comment by MichelChouinard** [comment]
Hi Cliff,

Please add a branch on v1.1.0.

I'll fork the repository again and check some stuff in it. Make sure that
everything is fine against supported PHP versions, correct if needed and
make minor revisions if needed. When finished we will be able to put it in
a release and clear the branch.

The PHP 7+ optimized version will be v2.0.0 and base on your latest PureMVC
ASC version. A dev branch base on the 1.1.0 version for starter but since
it wont be stable for a time should not be merged in MASTER in case some
existing forks decide to contribute.

I have projects ideas, and no more job. I think I can develop great things
on PureMVC. And now that I do not have a boss in my way I can decide what
framework I use.

One thing. Having no control over PureMVC/puremvc-php-multicore-framework
repository and associates utilities wont help on building community around
it. A thing I want to work on. It's like I'm the author of the port but no
one can commune with me from the original repository.

Also, the project fail comparison with recommended community standards
<https://opensource.guide/>. You can see what's missing at
https://github.com/PureMVC/puremvc-php-multicore-framework/community. That
is also one thing I'd like to address.  Plus, the API documentation is not
linked correctly and maybe we could use GitHub pages for this, not sure yet.

By the way, the site is great!!!  But the documentation should be readable
in HTML with ports API documentation accessible from it and I think it lack
something that I can't put my finger on yet but it's been trotting in my
head from a couple of weeks.  I'll keep you posted.




*Michel Chouinardmichel.chouinard@gmail.com <michel.chouinard@gmail.com>*
1068 Av Fournier
Québec  Qc  G1V 3M2
Canada

+1 418-255-9364


Le lun. 27 août 2018, à 10 h 16, Cliff Hall <notifications@github.com> a
écrit :

**Comment by cliffhall** [comment]
Shortly I will grant you access so that you can branch and merge the PHP repos.

**Pull request merged**
